# Generated by Django 5.0.6 on 2024-07-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='zip_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
