# Generated by Django 5.0.6 on 2024-07-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payment', '0003_shippingaddress_country_shippingaddress_phone_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shippingaddress',
            name='address2',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
